/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  school: [
    {
      type: 'autogenerated',
      dirName: 'all',
    },
  ],
  book: [
    {
      type: 'autogenerated',
      dirName: 'book',
    },
  ],
  chsc: [
    {
      type: 'category',
      label: '二階歷程檔案',
      link: {
        type: 'doc',
        id: 'chsc/intro',
      },
      collapsed: false,
      items: [
        'chsc/sum',
        'chsc/life',
        'chsc/epfo',
        'chsc/備審資料示範',
        'chsc/官方資料'
      ],
    },
    {
      type: 'link',
      label: '成功的反思', // The link label
      href: '/book/suc', // The internal path
    },
  ],
};

module.exports = sidebars;